apiVersion: apps/v1
kind: Deployment
metadata:
  name: riki-flask-dep
  labels:
    app: riki-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riki-flask
  template:
    metadata:
      labels:
        app: riki-flask
    spec:
      containers:
      - name: riki-flask
        image: rikimitra779/flaskdemo:hello
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: riki-flask-service
spec:
  selector:
    app: riki-flask
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
      nodePort: 31777